obj-$(FLOW_NODE_TYPE_GENERICANALOG) += genericanalog.mod
obj-genericanalog-$(FLOW_NODE_TYPE_GENERICANALOG) := genericanalog.json genericanalog.o
obj-genericanalog-$(FLOW_NODE_TYPE_GENERICANALOG)-type := flow
